In [3]:
import numpy as np

# Numpy used  for Array creation

## 1 . Using Python data collections [list, tuple, set] create numpy array
## 2.  Using Numpy default function for the creation Numpy arrays
## 3. Convert list, tuple to numpy arrays

In [8]:
# python list
# single dimension arrya
li = [1,2,3,4,5]
type(li)
# creastion of numpy array from list
np_li = np.array(li)
type(np_li)

## 2d dimensional array

li_2d = [[1,2,3,4,5], [1,2,3,4,5]]
np_2d = np.array(li_2d)
print(np_2d)
print(type(np_2d))

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>


# Diffrent Basic function with numpy arrays

# 1. shape
# 2 .ndim
# 3. dtype

In [11]:
print("shape of array",np_2d.shape)
print("dimensions of array",np_2d.ndim)
print("data type of array",np_2d.dtype)

shape of array (2, 5)
dimensions of array 2
data type of array int32


## 1. np.zeros
## 2. np.ones
## 3. np.arrange
## 4. np.random

In [20]:
zeros = np.zeros((2,5),dtype=int)
print(zeros)
print(zeros.shape)
print("ndim :")
print(zeros.ndim)
print("dtype")
print(zeros.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]]
(2, 5)
ndim :
2
dtype
int32


In [21]:
zeros = np.ones((2,5),dtype=int)
print(zeros)
print(zeros.shape)
print("ndim :")
print(zeros.ndim)
print("dtype")
print(zeros.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]]
(2, 5)
ndim :
2
dtype
int32


In [29]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.random.random((3,3))

array([[0.1292537 , 0.40760633, 0.76964725],
       [0.8286329 , 0.38018929, 0.65908127],
       [0.35376307, 0.06639942, 0.93274224]])

# work on slicing 

In [33]:
arr = np.arange(10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[0]

0

In [38]:
len(arr)

10

In [39]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
## mathematical operations

arr1 = np.arange(5)
print(arr1)
arrr2 = np.arange(5)
print(arrr2)
arr3 = arr1 + arrr2
arr3 = arr1 * arrr2
print(arr3)

[0 1 2 3 4]
[0 1 2 3 4]
[ 0  1  4  9 16]


In [50]:
print("mean",arr3.mean())
print("max",arr3.max())
print("min",arr3.min())
print("standart devation", arr3.std())

mean 6.0
max 16
min 0
standart devation 5.89915248150105


# Reshaping the array

In [51]:
arr.shape

(10,)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
arr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
arr.reshape((5,3))

ValueError: cannot reshape array of size 10 into shape (5,3)